### ISSUE TITLE
 GPU support with ARM architecture in Ant Media server

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4417]
### Short description
Ant Media server does not use GPU when installed on ARM architecture. I used Graviton based GPU instance (g5g) on AWS.

### Environment

* Operating system and version: Ubuntu 20.04
* Ant Media Server version: v2.4.3

### Steps to reproduce
1. Launch the graviton based GPU server **(g5g.xlarge)** using community image **(ami-02c9aba5b22a6388a - Deep Learning AMI Graviton GPU CUDA 11.4.2 (Ubuntu 20.04) 20211119).**
2. Install the Ant media server
3. Enable ABR
4. Publish the stream and check the **nvidia-smi** output

### Expected behavior
Ant Media server should use GPU

### Actual behavior
Ant Media server is not using GPU

**Comment by useronym** [comment]
We are facing the same issue on a Nvidia Jetson Nano (ARM64).

Please note that `nvidia-smi` is architecture-specific. On a Tegra GPU, such as the one Jetson Nano uses, `nvidia-smi` is not supported. Tegra has the alternative `tegrastats` command.

A better way to check for CUDA support seems to be the `nvcc --version` command, which will verify that the CUDA compiler is installed, and this command is not dependent on the GPU architecture.

**Comment by yashtandon113** [comment]
GPU is now working with Ant Media Server on **arm64** architecture, as tested. Please see the following information:

**AMS version:** Latest snapshot (Enterprise Edition 2.6.0-SNAPSHOT 20230214_0952)
**Instance type:** G5g.xlarge (Graviton servers with arm64 architecture) on AWS
**OS version:** Ubuntu 22.04

Installation steps to install CUDA on Ubuntu 22.04 with ARM.

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/sbsa/cuda-keyring_1.0-1_all.deb
sudo dpkg -i cuda-keyring_1.0-1_all.deb
sudo apt-get update
sudo apt-get -y install cuda
```

![image](https://user-images.githubusercontent.com/82374739/219887133-412a6285-674d-458e-a6f2-56182f0f9ccf.png)

**NOTE:** The server did not use the GPU driver automatically. I had to change the encoder name in the _red5-web.properties_ file by adding the below property in the _/usr/loca/antmedia/webapps/LiveApp/WEB-INF_ folder.

`settings.encoding.encoderName=h264_nvenc`

**Comment by mekya** [comment]
Could you please check the same in x64 architecture? @yashtandon113

**Comment by mekya** [comment]
Thank you @yashtandon113 for making it clear. 

Could you please create another issue for this problem?

**Comment by yashtandon113** [comment]
The Git Hub issue is created for the GPU problem --> https://github.com/ant-media/Ant-Media-Server/issues/4893

I am closing this issue.
